vich_uploader:
    db_driver: orm
    mappings:
        posters:
            uri_prefix: /images/posters
            upload_destination: '%kernel.project_dir%/public/images/posters'
        movieScreens:
            uri_prefix: /images/movie-screens
            upload_destination: '%kernel.project_dir%/public/images/movie-screens'
        movieCategory:
            uri_prefix: /images/movie-category
            upload_destination: '%kernel.project_dir%/public/images/movie-category'
        cinemas:
            uri_prefix: /images/cinemas
            upload_destination: '%kernel.project_dir%/public/images/cinemas'
